version: '3'

services: 
  flask_kb: 
   container_name: flask_kb
   build: ./flask_kb
   ports:
    - "5000:5000"
   command: gunicorn -b 0.0.0.0:5000 -w 1 run

  nginx:
   container_name: nginx
   build: ./nginx
   ports:
    - "80:80"
   depends_on: 
    - flask_kb
